# Generated by Django 5.2.9 on 2026-01-05 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_carmodeltrim_trim_body_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDrivetrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_gearbox', models.CharField(choices=[('MANTRANS', 'Manual'), ('AUTOTRANS', 'Automatic'), ('SEQ', 'Sequential'), ('DCT', 'Automatic - Dual Clutch'), ('CVT', 'Continually Variable')], max_length=10)),
                ('car_gear_no', models.PositiveIntegerField()),
                ('car_powertrain', models.CharField(choices=[('FOUR', 'Four Wheel Drive'), ('ALLW', 'All Wheel Drive'), ('FRONT', 'Front Wheel Drive'), ('REAR', 'Rear Wheel Drive')], max_length=10)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivetrain', to='core.carmodel')),
            ],
        ),
    ]
