# Generated by Django 5.2.9 on 2026-01-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_cardrivetrain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardrivetrain',
            name='car_powertrain',
            field=models.CharField(choices=[('EIGHT', 'Eight Wheel Drive'), ('SIX', 'Six Wheel Drive'), ('FOUR', 'Four Wheel Drive'), ('ALLW', 'All Wheel Drive'), ('FRONT', 'Front Wheel Drive'), ('REAR', 'Rear Wheel Drive')], max_length=10),
        ),
    ]
