# Generated by Django 5.2.9 on 2026-01-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_cardrivetrain_car_powertrain'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodeltrim',
            name='trim_drivetrain',
            field=models.ManyToManyField(related_name='trim_drivetrain', to='core.cardrivetrain'),
        ),
    ]
