# Generated by Django 5.2.9 on 2026-01-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_carmodeltrim_trim_drivetrain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodeltrim',
            name='trim_drivetrain',
            field=models.ManyToManyField(blank=True, related_name='trim_drivetrain', to='core.cardrivetrain'),
        ),
    ]
