# Generated by Django 5.2.9 on 2026-01-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_carmodeltrim_trim_drivetrain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardrivetrain',
            name='car_gearbox',
            field=models.CharField(choices=[('MANTRANS', 'Manual'), ('AUTOTRANS', 'Automatic'), ('SEQ', 'Sequential'), ('DCT', 'Automatic - Dual Clutch'), ('CVT', 'Continually Variable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cardrivetrain',
            name='car_powertrain',
            field=models.CharField(choices=[('EIGHT', 'Eight Wheel Drive'), ('SIX', 'Six Wheel Drive'), ('FOUR', 'Four Wheel Drive'), ('ALLW', 'All Wheel Drive'), ('FRONT', 'Front Wheel Drive'), ('REAR', 'Rear Wheel Drive')], max_length=20),
        ),
        migrations.AlterField(
            model_name='carmodeltrim',
            name='trim_drivetrain',
            field=models.ManyToManyField(related_name='trim_drivetrain', to='core.cardrivetrain'),
        ),
    ]
