# Generated by Django 5.2.9 on 2026-01-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_cardrivetrain_car_gearbox_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardrivetrain',
            name='car_gearbox',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AUTO', 'Automatic'), ('SEQ', 'Sequential'), ('DCT', 'Automatic - Dual Clutch'), ('CVT', 'Continually Variable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cardrivetrain',
            name='car_powertrain',
            field=models.CharField(choices=[('8WD', 'Eight Wheel Drive'), ('6WD', 'Six Wheel Drive'), ('4WD', 'Four Wheel Drive'), ('AWD', 'All Wheel Drive'), ('FWD', 'Front Wheel Drive'), ('RwD', 'Rear Wheel Drive')], max_length=20),
        ),
    ]
