# Generated by Django 5.2.9 on 2026-01-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_cardrivetrain_car_gearbox_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facelift',
            name='changes_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
