# Generated by Django 5.2.9 on 2026-01-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_facelift_changes_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_vanilla_modded',
            field=models.CharField(choices=[('VAN', 'Vanilla'), ('MOD', 'Modded')], default=0, max_length=7),
            preserve_default=False,
        ),
    ]
